modules:
  api:
    profile: humanitec/default-module
    spec:
      containers:
        main:
          id: main
          image: ghcr.io/acme/api:v2
  worker:
    profile: humanitec/default-module
    spec:
      containers:
        main:
          id: main
          image: ghcr.io/acme/worker:v7
