apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: bucket-default
entity:
  name: bucket-default
  type: bucket
  driver_type: humanitec/terraform
  criteria:
  - {}
  driver_account: fixture-account
  driver_inputs:
    values:
      source:
        url: https://fixtures.invalid/bucket.git
        rev: v1
      variables:
        subnet_id: ${resources['network.default#shared.vpc'].outputs.subnet_id}
