apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: network-default
entity:
  name: network-default
  type: network
  driver_type: humanitec/terraform
  criteria:
  - {}
  driver_account: fixture-account
  driver_inputs:
    values:
      source:
        url: https://fixtures.invalid/network.git
        rev: v1
      variables:
        db_host: ${resources['postgres.default#modules.api.externals.db'].outputs.host}
