modules:
  api:
    profile: humanitec/default-module
    spec:
      containers:
        main:
          id: main
          image: ghcr.io/acme/api:v1
    externals:
      cfg:
        type: config
        class: default
      data:
        type: bucket
        class: default
        params:
          region: ${externals.cfg.region}
