apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: redis-default
entity:
  name: redis-default
  type: redis
  driver_type: humanitec/terraform
  criteria:
  - {}
  driver_account: fixture-account
  driver_inputs:
    values:
      source:
        url: https://fixtures.invalid/redis.git
        rev: v1
