apiVersion: entity.humanitec.io/v1b1
kind: ResourceType
metadata:
  id: config
entity:
  inputs_schema:
    type: object
    properties: {}
    additionalProperties: false
  outputs_schema:
    type: object
    properties:
      value:
        type: string
      region:
        type: string
    additionalProperties: false
