apiVersion: challenge.humanitec.io/v1alpha1
kind: PlannerCase
metadata:
  name: 24-remove-workload
spec:
  context: context.yaml
  currentDeploymentSet: current-deployment-set.yaml
  beforeScore: before.score.yaml
  afterScore: null
  resourceTypes:
  - resource-types/workload.yaml
  resourceDefinitions:
  - resource-definitions/workload-default.yaml
  activeResources: active-resources.yaml
  terraformSourceMap: []
