apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: postgres-default
entity:
  name: postgres-default
  type: postgres
  driver_type: humanitec/terraform
  criteria:
  - {}
  driver_account: fixture-account
  driver_inputs:
    values:
      source:
        url: https://fixtures.invalid/postgres.git
        rev: v1
      variables:
        subnet_id: ${resources['network.default#shared.vpc'].outputs.missing}
