// Package scorek8s runs a pinned renderer in a private disposable workspace.
// It never provisions infrastructure or passes credential bytes to score-k8s.
package scorek8s

import (
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
	"orchestrator/internal/adapters/kubernetes"
	"orchestrator/internal/domain/resource"
	"orchestrator/internal/ports/execution"
)

const BundleID = "score-k8s-internal-v1"
const Version = "0.15.0"

// Fingerprint the adapter as well as the fixed output-only provisioner.
//
//go:embed renderer.go provisioners.yaml
var bundleFiles embed.FS

type Renderer struct {
	path   string
	bundle resource.RenderBundle
	native execution.WorkloadRenderer
}

func New(ctx context.Context, path string, native execution.WorkloadRenderer) (*Renderer, error) {
	resolved, err := exec.LookPath(path)
	if err != nil {
		return nil, fmt.Errorf("score-k8s: configured binary unavailable")
	}
	resolved, err = filepath.Abs(resolved)
	if err != nil {
		return nil, err
	}
	resolved, err = filepath.EvalSymlinks(resolved)
	if err != nil {
		return nil, err
	}
	ctx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, resolved, "--version")
	cmd.Env = []string{"PATH=" + filepath.Dir(resolved), "LANG=C"}
	version, err := cmd.Output()
	if err != nil || !strings.HasPrefix(string(version), "score-k8s "+Version+" (") {
		return nil, fmt.Errorf("score-k8s: binary must be version %s", Version)
	}
	digest, err := binaryDigest(resolved)
	if err != nil {
		return nil, err
	}
	source, _ := bundleFiles.ReadFile("renderer.go")
	provisioner, _ := bundleFiles.ReadFile("provisioners.yaml")
	h := sha256.New()
	h.Write([]byte(Version))
	h.Write([]byte(digest))
	h.Write(source)
	h.Write(provisioner)
	return &Renderer{path: resolved, native: native, bundle: resource.RenderBundle{ID: BundleID, Version: Version, BinaryDigest: digest, Digest: hex.EncodeToString(h.Sum(nil))}}, nil
}
func (r *Renderer) Bundles() map[string]resource.RenderBundle {
	return map[string]resource.RenderBundle{BundleID: r.bundle}
}
func binaryDigest(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("score-k8s: binary unavailable")
	}
	defer f.Close()
	h := sha256.New()
	if _, err = io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}
func (r *Renderer) ValidateSelection(ctx context.Context, selected resource.RenderingSelection) error {
	if err := ctx.Err(); err != nil {
		return err
	}
	if selected.DriverType == "" {
		return nil
	}
	if selected.DriverType != resource.DriverScoreK8s || selected.Bundle != r.bundle || selected.DefinitionKey == "" || selected.DefinitionHash == "" {
		return fmt.Errorf("score-k8s: pinned rendering selection is unavailable")
	}
	digest, err := binaryDigest(r.path)
	if err != nil {
		return err
	}
	if digest != r.bundle.BinaryDigest {
		return fmt.Errorf("score-k8s: binary changed; restart and preview again")
	}
	return nil
}

func (r *Renderer) Render(ctx context.Context, req execution.RenderRequest) ([]execution.Manifest, error) {
	if req.Selection.DriverType == "" {
		return r.native.Render(ctx, req)
	}
	if err := r.ValidateSelection(ctx, req.Selection); err != nil {
		return nil, err
	}
	// Reuse shared product policies for Secret delivery, Agent annotations, defaults
	// and identity. Deployment/Service are generated by score-k8s from normalized Score.
	policy, err := kubernetes.NewRenderer().Render(ctx, req)
	if err != nil {
		return nil, err
	}
	doc, patches, extras, err := normalize(req, policy)
	if err != nil {
		return nil, err
	}
	workspace, err := os.MkdirTemp("", "orchestrator-score-k8s-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(workspace)
	provisioner, _ := bundleFiles.ReadFile("provisioners.yaml")
	scoreBytes, err := json.Marshal(doc)
	if err != nil {
		return nil, err
	}
	// The JSON is template DATA, quoted as a Go string; user values cannot become templates.
	var template strings.Builder
	for _, p := range patches {
		value, err := json.Marshal(p["value"])
		if err != nil {
			return nil, err
		}
		template.WriteString("{{ range $i, $m := .Manifests }}{{ if eq $m.kind " + strconv.Quote(p["kind"].(string)) + " }}\n- op: set\n  path: {{ $i }}." + p["path"].(string) + "\n  value: {{ " + strconv.Quote(string(value)) + " }}\n{{ end }}{{ end }}\n")
	}
	patchTemplate := []byte(template.String())
	for name, content := range map[string][]byte{"score.json": scoreBytes, "provisioners.yaml": provisioner, "patch.tpl": patchTemplate} {
		if err := os.WriteFile(filepath.Join(workspace, name), content, 0600); err != nil {
			return nil, err
		}
	}
	ctx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()
	run := func(args ...string) error {
		cmd := exec.CommandContext(ctx, r.path, args...)
		cmd.Dir = workspace
		// No host tokens, kubeconfig, Terraform or Git credentials inherited.
		cmd.Env = []string{"PATH=" + filepath.Dir(r.path), "HOME=" + workspace, "TMPDIR=" + workspace, "LANG=C"}
		if err := cmd.Run(); err != nil {
			if ctx.Err() != nil {
				return ctx.Err()
			}
			return fmt.Errorf("score-k8s: generation failed")
		}
		return nil
	}
	if err := run("init", "--quiet", "--no-sample", "--no-default-provisioners", "--provisioners", filepath.Join(workspace, "provisioners.yaml"), "--patch-templates", filepath.Join(workspace, "patch.tpl")); err != nil {
		return nil, err
	}
	if err := run("generate", "--quiet", "score.json", "--namespace", req.Namespace, "--output", "manifests.yaml"); err != nil {
		return nil, err
	}
	file, err := os.Open(filepath.Join(workspace, "manifests.yaml"))
	if err != nil {
		return nil, err
	}
	defer file.Close()
	decoder := yaml.NewDecoder(io.LimitReader(file, 8<<20))
	generated := []execution.Manifest{}
	seen := map[string]bool{}
	for {
		var object map[string]any
		err := decoder.Decode(&object)
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("score-k8s: invalid manifest output")
		}
		if len(object) == 0 {
			continue
		}
		kind, _ := object["kind"].(string)
		api, _ := object["apiVersion"].(string)
		meta, _ := object["metadata"].(map[string]any)
		name, _ := meta["name"].(string)
		namespace, _ := meta["namespace"].(string)
		if (kind != "Deployment" && kind != "Service") || name != req.WorkloadID || namespace != req.Namespace || seen[kind] || (kind == "Deployment" && api != "apps/v1") || (kind == "Service" && api != "v1") {
			return nil, fmt.Errorf("score-k8s: generated object violates workload identity/namespace/kind contract")
		}
		seen[kind] = true
		generated = append(generated, execution.Manifest{APIVersion: api, Kind: kind, Name: name, Namespace: namespace, Object: object})
	}
	if !seen["Deployment"] || seen["Service"] != (req.Module.Spec.Service != nil && len(req.Module.Spec.Service.Ports) > 0) {
		return nil, fmt.Errorf("score-k8s: incomplete generated workload")
	}
	restoreEmptyEnv(generated, policy)
	if err := validateObjects(generated, policy); err != nil {
		return nil, err
	}
	return append(extras, generated...), nil
}

func normalize(req execution.RenderRequest, policy []execution.Manifest) (map[string]any, []map[string]any, []execution.Manifest, error) {
	doc := map[string]any{"apiVersion": "score.dev/v1b1", "metadata": map[string]any{"name": req.WorkloadID}}
	containers := map[string]any{}
	bindings := map[string]any{}
	patches := []map[string]any{}
	extras := []execution.Manifest{}
	// Patches select manifests by kind rather than numeric output order.
	for _, m := range policy {
		if m.Kind != "Deployment" && m.Kind != "Service" {
			extras = append(extras, m)
			continue
		}
		spec := m.Object["spec"].(map[string]any)
		if m.Kind == "Deployment" {
			pod := spec["template"].(map[string]any)["spec"].(map[string]any)
			for _, entry := range pod["containers"].([]any) {
				c := entry.(map[string]any)
				name := c["name"].(string)
				normalized := map[string]any{"image": c["image"], "resources": c["resources"]}
				for _, field := range []string{"command", "args"} {
					if value, ok := c[field]; ok {
						normalized[field] = value
					}
				}
				vars := map[string]any{}
				if env, ok := c["env"].([]any); ok {
					for _, entry := range env {
						e := entry.(map[string]any)
						key := "b" + strconv.Itoa(len(bindings))
						binding := map[string]any{"secret": false}
						if value, ok := e["value"]; ok {
							binding["value"] = escapeScore(value)
						} else {
							ref := e["valueFrom"].(map[string]any)["secretKeyRef"].(map[string]any)
							binding = map[string]any{"secret": true, "name": ref["name"], "key": ref["key"]}
						}
						bindings[key] = binding
						vars[e["name"].(string)] = "${resources.bindings." + key + "}"
					}
				}
				if len(vars) > 0 {
					normalized["variables"] = vars
				}
				for _, field := range []string{"readinessProbe", "livenessProbe"} {
					if value, ok := c[field]; ok {
						normalized[field] = map[string]any{"httpGet": value.(map[string]any)["httpGet"]}
					}
				}
				containers[name] = normalized
			}
			// Controlled platform patches preserve defaults, Agent delivery and workload identity.
			patches = append(patches, patch("Deployment", "metadata", m.Object["metadata"]), patch("Deployment", "spec.replicas", spec["replicas"]), patch("Deployment", "spec.selector", spec["selector"]), patch("Deployment", "spec.template.metadata", spec["template"].(map[string]any)["metadata"]))
			for _, field := range []string{"imagePullSecrets", "serviceAccountName"} {
				if value, ok := pod[field]; ok {
					patches = append(patches, patch("Deployment", "spec.template.spec."+field, value))
				}
			}
			for i, entry := range pod["containers"].([]any) {
				c := entry.(map[string]any)
				for _, field := range []string{"imagePullPolicy", "ports", "readinessProbe", "livenessProbe"} {
					if value, ok := c[field]; ok {
						patches = append(patches, patch("Deployment", "spec.template.spec.containers."+strconv.Itoa(i)+"."+field, value))
					}
				}
			}
		} else {
			ports := map[string]any{}
			for _, entry := range spec["ports"].([]any) {
				p := entry.(map[string]any)
				ports[p["name"].(string)] = map[string]any{"port": p["port"], "targetPort": p["targetPort"], "protocol": p["protocol"]}
			}
			doc["service"] = map[string]any{"ports": ports}
			patches = append(patches, patch("Service", "metadata", m.Object["metadata"]), patch("Service", "spec.type", spec["type"]), patch("Service", "spec.selector", spec["selector"]))
		}
	}
	doc["containers"] = containers
	if len(bindings) > 0 {
		doc["resources"] = map[string]any{"bindings": map[string]any{"type": "orchestrator-bindings", "params": bindings}}
	}
	// Convert kind markers into a protected template. Dynamic JSON data stays quoted.
	return doc, patches, extras, nil
}

// restoreEmptyEnv puts back explicit empty plain values. score-k8s omits an
// empty variable's value; the native policy emits value "". Only entries named
// by the policy for the same container, with neither value nor valueFrom, change;
// validateObjects then still compares the complete env with the policy.
func restoreEmptyEnv(generated, policy []execution.Manifest) {
	empty := map[string]map[string]bool{}
	for _, c := range podContainers(policy) {
		for _, item := range asList(c["env"]) {
			e, _ := item.(map[string]any)
			if v, ok := e["value"].(string); ok && v == "" {
				name, _ := c["name"].(string)
				if empty[name] == nil {
					empty[name] = map[string]bool{}
				}
				empty[name][e["name"].(string)] = true
			}
		}
	}
	for _, c := range podContainers(generated) {
		cn, _ := c["name"].(string)
		for _, item := range asList(c["env"]) {
			e, _ := item.(map[string]any)
			name, _ := e["name"].(string)
			_, hasValue := e["value"]
			_, hasFrom := e["valueFrom"]
			if empty[cn][name] && !hasValue && !hasFrom {
				e["value"] = ""
			}
		}
	}
}
func asList(v any) []any { l, _ := v.([]any); return l }
func podContainers(ms []execution.Manifest) []map[string]any {
	out := []map[string]any{}
	for _, m := range ms {
		if m.Kind != "Deployment" {
			continue
		}
		spec, _ := m.Object["spec"].(map[string]any)
		tpl, _ := spec["template"].(map[string]any)
		pod, _ := tpl["spec"].(map[string]any)
		for _, entry := range asList(pod["containers"]) {
			if c, ok := entry.(map[string]any); ok {
				out = append(out, c)
			}
		}
	}
	return out
}
func patch(kind, path string, value any) map[string]any {
	return map[string]any{"op": "set", "path": path, "value": value, "kind": kind}
}
func escapeScore(value any) any {
	switch v := value.(type) {
	case []any:
		out := make([]any, len(v))
		for i, x := range v {
			out[i] = escapeScore(x)
		}
		return out
	case string:
		return strings.ReplaceAll(v, "$", "$$")
	default:
		return value
	}
}

// Compare protected product semantics with the shared renderer policy. The
// comparison includes secretKeyRefs and prevents surprise namespaces or resources.
func validateObjects(generated, policy []execution.Manifest) error {
	byKind := map[string]map[string]any{}
	for _, m := range policy {
		byKind[m.Kind] = m.Object
	}
	for _, m := range generated {
		expected := byKind[m.Kind]
		for _, field := range []string{"metadata", "spec"} {
			// Extra upstream rollout defaults are allowed; protected fields must match.
			if !contains(m.Object[field], expected[field]) {
				return fmt.Errorf("score-k8s: generated workload violates protected product fields")
			}
		}
		if m.Kind == "Deployment" {
			actualPod := m.Object["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any)
			expectedPod := expected["spec"].(map[string]any)["template"].(map[string]any)["spec"].(map[string]any)
			for _, field := range []string{"volumes", "initContainers"} {
				if _, ok := actualPod[field]; ok && expectedPod[field] == nil {
					return fmt.Errorf("score-k8s: unexpected pod configuration")
				}
			}
			expectedContainers := expectedPod["containers"].([]any)
			for _, entry := range actualPod["containers"].([]any) {
				container := entry.(map[string]any)
				for _, field := range []string{"envFrom", "volumeMounts"} {
					if _, ok := container[field]; ok {
						return fmt.Errorf("score-k8s: unexpected container configuration")
					}
				}
				for _, entry := range expectedContainers {
					wanted := entry.(map[string]any)
					if container["name"] == wanted["name"] && (!contains(container["env"], wanted["env"]) || !contains(wanted["env"], container["env"])) {
						return fmt.Errorf("score-k8s: unexpected environment/Secret binding")
					}
				}
			}
		}

	}
	return nil
}
func contains(actual, expected any) bool {
	switch e := expected.(type) {
	case map[string]any:
		a, ok := actual.(map[string]any)
		if !ok {
			return false
		}
		for k, v := range e {
			if !contains(a[k], v) {
				return false
			}
		}
		return true
	case []any:
		a, ok := actual.([]any)
		if !ok || len(a) != len(e) {
			return false
		}
		for i, v := range e {
			actualEntry := a[i]
			if named, ok := v.(map[string]any); ok && named["name"] != nil {
				found := false
				for _, entry := range a {
					if candidate, ok := entry.(map[string]any); ok && candidate["name"] == named["name"] {
						actualEntry = candidate
						found = true
						break
					}
				}
				if !found {
					return false
				}
			}
			if !contains(actualEntry, v) {
				return false
			}
		}
		return true
	default:
		a, _ := json.Marshal(actual)
		b, _ := json.Marshal(expected)
		return string(a) == string(b)
	}
}
